---
name: Docs

"on":
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.12"

      - name: Install MkDocs dependencies
        run: pip install -r docs/requirements.txt

      - name: Build docs
        run: mkdocs build --strict
